name: Push commit
on:
   push:
    branches:
      - master
   schedule: # Run workflow automatically
    - cron: '* * * * *' # Runs every min, on the min
   workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name sroy96
          git config --global user.email sauravroy.eee@gmail.com'
          git commit -am "Automated report"
          git push
